image: "python:3.8"

services:
  - postgres:11.7
variables:
  POSTGRES_DB: testdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - python --version
  - pip install pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env

stages:
  - Static Analysis
  - Test
  
flake8:
  stage: Static Analysis
  script:
  - pipenv run flake8 .

pytest:
  stage: Test
  script:
    - pipenv run pytest --cov=app

after_script:
  - pipenv run codecov